services:
  postgres-demo:
    image: postgres:15.3-alpine
    restart: 'always'
    container_name: postgres-demo
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  krakend:
    image: devopsfaith/krakend:latest
    container_name: krakend
    ports:
      - 9191:9191
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    command: run -d -c /etc/krakend/krakend.json

  bff-service:
    build:
      context: .
      args:
        JAR_FILE: ./bff-service/target/bff-service-0.0.1-SNAPSHOT.jar
    container_name: bff-service
    environment:
      #Adapter configuration
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT_SWAGGER: ${SERVER_PORT_SWAGGER}
      SERVER_PORT_USER: ${SERVER_PORT_USER}
      SERVER_EXTERNAL_PORT: ${SERVER_EXTERNAL_PORT}
      SERVER_PORT_WALLET: ${SERVER_PORT_WALLET}
      SERVER_PORT_ITEM: ${SERVER_PORT_ITEM}
      SERVER_PORT_TRANSFER: ${SERVER_PORT_TRANSFER}
    ports:
      - "${SERVER_PORT_BFF}:${SERVER_PORT_BFF}"