package com.trade.free.dto.enums;

public enum EventConductorType {
    HOLD_ITEM_REQUEST,
    HOLD_ITEM_SUCCESSFULLY,
    HOLD_ITEM_FAILED,
    UN_HOLD_ITEM_REQUEST,
    TRANSFER_AMOUNT_REQUEST,
    TRANSFER_AMOUNT_SUCCESSFULLY,
    TRANSFER_AMOUNT_FAILED,
    SELL_ITEM_REQUEST,
    SELL_ITEM_SUCCESSFULLY
}
